=== dealy14/LearningFox-LMS/anlm/uploadfiles/course-11/scos/5/p2sco.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by Germano Giuliani (ETH Zurich) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:group name="formattedtext">
		<xs:choice>
			<xs:element ref="b"/>
			<xs:element ref="big"/>
			<xs:element ref="i"/>
			<xs:element ref="p"/>
			<xs:element ref="s"/>
			<xs:element ref="small"/>
			<xs:element ref="strike"/>
			<xs:element ref="sub"/>
			<xs:element ref="sup"/>
			<xs:element ref="u"/>
			<xs:element ref="br"/>
		</xs:choice>
	</xs:group>
	<xs:attributeGroup name="identifiers">
		<xs:attribute name="name" type="xs:string"/>
	</xs:attributeGroup>
	<xs:element name="audio">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title" minOccurs="0"/>
				<xs:element ref="description"/>
			</xs:sequence>
			<xs:attributeGroup ref="identifiers"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="author">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="b">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="bibitem">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="description"/>
				<xs:element ref="details"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="big">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="br">
		<xs:complexType/>
	</xs:element>
	<xs:element name="choice">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="option" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="city">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="date">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="definition">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="definitionlist">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title" minOccurs="0"/>
				<xs:element ref="description" minOccurs="0"/>
				<xs:sequence maxOccurs="unbounded">
					<xs:element ref="term"/>
					<xs:element ref="definition"/>
				</xs:sequence>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="description">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="hinttext">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="hintdetails">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="details">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="author"/>
				<xs:element ref="title"/>
				<xs:element ref="editor"/>
				<xs:element ref="etitle"/>
				<xs:element ref="publisher"/>
				<xs:element ref="city"/>
				<xs:element ref="date"/>
				<xs:element ref="pages"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="document">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title" minOccurs="0"/>
				<xs:element ref="description"/>
			</xs:sequence>
			<xs:attributeGroup ref="identifiers"/>
			<xs:attribute name="file"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="thumbnail">
		<xs:complexType>
			<xs:attributeGroup ref="identifiers"/>
			<xs:attribute name="file"/>
			<xs:attribute name="width"/>
			<xs:attribute name="height"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="picture">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title" minOccurs="0"/>
				<xs:element ref="thumbnail" minOccurs="0"/>
				<xs:element ref="description"/>
			</xs:sequence>
			<xs:attributeGroup ref="identifiers"/>
			<xs:attribute name="file"/>
			<xs:attribute name="width"/>
			<xs:attribute name="height"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="mediafile">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title" minOccurs="0"/>
				<xs:element ref="description"/>
			</xs:sequence>
			<xs:attributeGroup ref="identifiers"/>
			<xs:attribute name="file"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="editor">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="enumeration">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title" minOccurs="0"/>
				<xs:element ref="description"/>
				<xs:element ref="listitem" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="etitle">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="explain">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="hint">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="hinttext"/>
				<xs:element ref="hintdetails" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="htmlblock">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="name" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="i">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="interaction">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="question"/>
				<xs:choice>
					<xs:element ref="choice"/>
					<xs:element ref="associate"/>
					<xs:element ref="likert"/>
					<xs:element ref="textentry"/>
					<xs:element ref="fillinthegaps"/>
				</xs:choice>
			</xs:sequence>
			<xs:attributeGroup ref="identifiers"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="listitem">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="itemization">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title" minOccurs="0"/>
				<xs:element ref="description" minOccurs="0"/>
				<xs:element ref="listitem" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="learningobject">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title"/>
				<xs:element ref="description"/>
				<xs:element ref="objectives"/>
				<xs:choice>
					<xs:element ref="part" maxOccurs="unbounded"/>
					<xs:element ref="learningstep" maxOccurs="unbounded"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="learningstep">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title" minOccurs="0"/>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="paragraph"/>
					<xs:element ref="htmlblock"/>
					<xs:element ref="audio"/>
					<xs:element ref="hint"/>
					<xs:element ref="interaction"/>
					<xs:element ref="quotation"/>
					<xs:element ref="bibitem"/>
					<xs:element ref="definitionlist"/>
					<xs:element ref="document"/>
					<xs:element ref="enumeration"/>
					<xs:element ref="itemization"/>
					<xs:element ref="picture"/>
					<xs:element ref="link"/>
					<xs:element ref="mediafile"/>
				</xs:choice>
			</xs:sequence>
			<xs:attributeGroup ref="identifiers"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="gap">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="option"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="likert">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="option" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="link">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title" minOccurs="0"/>
				<xs:element ref="description" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="href" type="xs:anyURI" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="associate">
		<xs:complexType>
			<xs:sequence>
				<xs:sequence maxOccurs="unbounded">
					<xs:element ref="this"/>
				</xs:sequence>
				<xs:sequence minOccurs="2" maxOccurs="unbounded">
					<xs:element ref="that"/>
				</xs:sequence>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fillinthegaps">
		<xs:complexType mixed="true">
			<xs:choice maxOccurs="unbounded">
				<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
				<xs:element ref="gap"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="this">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
			<xs:attribute name="idx" type="xs:string" use="required"/>
			<xs:attribute name="match" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="option">
		<xs:complexType mixed="true">
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="explain"/>
			</xs:sequence>
			<xs:attribute name="correct" use="optional" default="false">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="false"/>
						<xs:enumeration value="true"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="part">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title"/>
				<xs:element ref="description"/>
				<xs:element ref="objectives"/>
				<xs:element ref="learningstep" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="that">
		<xs:complexType mixed="true">
			<xs:attribute name="idx" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="pages" type="xs:string"/>
	<xs:element name="paragraph">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="objectives">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="p">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="possibleanswer">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="publisher">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="question">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="quotation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="quote"/>
				<xs:element ref="source"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="quote">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="s">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="small">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="source">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="strike">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="sub">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="sup">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="term">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="textentry">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="possibleanswer" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="title">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="u">
		<xs:complexType mixed="true">
			<xs:group minOccurs="0" maxOccurs="unbounded" ref="formattedtext"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== dealy14/LearningFox-LMS/anlm/uploadfiles/course-12/scos/2/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<learningobject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".//p2sco.xsd">
	<title>
		Dimensions of Security in the Information Age 
	</title>
	<description>
		In order to explain the various aspects of security in the 
		information age, this module first describes the growing 
		dependence of society on information and communications 
		technology (ICT) and the ensuing vulnerability of so-called 
		critical information infrastructures. The module then outlines 
		the changed nature of the information age security environment 
		and how such change has increased the likelihood of 
		computer-based attacks. The module also explores the various 
		motives of attackers and discusses &quot;cyber-terrorism&quot;. 
		Finally, various tools and methods that are commonly used for 
		intruding into computer systems are discussed. 
	</description>
	<objectives>
		The aim of the module is that students understand the relevance 
		of computer-based attacks to the security policies of nation 
		states. When you have completed the module, you will understand 
		what critical information infrastructures are and how these 
		affect the functioning of modern societies. Further, you will 
		have gained insight into the ways in which information age risks
		are changing. You will also know how various types of hackers 
		work, according to their various motives for attacking 
		particular systems, and you will be informed about the methods 
		they use for launching attacks on computer systems. 
	</objectives>
	<learningstep>
		<paragraph>
			On 25 January 2003, global Internet traffic slowed to a 
			crawl as a virus-like worm called Sapphire or SQL 
			Slammer worked its way around the world. The new worm 
			exploited a flaw in Microsoft's SQL Server 2000. The 
			server that had been attacked randomly sought out other 
			computers that ran a Microsoft SQL server. The infected 
			servers then sought out more computers and infected 
			them. The process created a considerable amount of 
			Internet traffic and brought parts of the Internet to a 
			standstill. 
		</paragraph>
		<paragraph>
			At the time, Sapphire was the fastest computer worm in 
			history. As it began to spread throughout the Internet, 
			the number of affected computers doubled every 8.5 
			seconds. It infected more than 90 per cent of its hosts 
			within 10 minutes; 5 of the 13 domain name servers were 
			offline as a result of the huge number of requests made 
			by the worm. 
		</paragraph>
		<link href="http://www.caida.org/analysis/security/sapphire/sapphire-2f-30m-2003-01-25.gif">
			<title>
				Sapphire 
			</title>
			<description>
				Follow the link to the Cooperative Association 
				for Internet Data Analysis (CAIDA) to watch the 
				astonishing spread of the Sapphire/SQL Slammer 
				worm over a half-hour period. 
			</description>
		</link>
		<paragraph>
			According to experts, the frequency of new worms and 
			viruses is increasing and will likely continue to do so 
			in future. The costs associated with worms and viruses 
			are significant: A market intelligence company in 
			London, Mi2g, has estimated that the Sapphire/SQL 
			Slammer worm caused between $950 million and $1.2 
			billion worldwide in lost productivity in its first five
			days. That puts the worm at No. 9 on the company's list 
			of most costly malicious code (for example, programs for
			worms and viruses), behind, for example, the Code Red 
			worm, with around $2.6 billion in productivity loss; the
			Love Letter virus, with $8.8 billion; and the Klez 
			virus, with $9.0 billion. 
		</paragraph>
		<paragraph>
			The considerable costs associated with worms and viruses
			and the frequency of their occurrence are the two main 
			reasons for the public attention they get. But there are
			many more threats to security in the information age 
			than just viruses or worms. In fact, a great many 
			factors are involved in information age security, and a 
			vast number of very different issues are discussed under
			the same heading. This lesson introduces the most 
			important of these issues. However, there is one common 
			denominator: the thorough dependence of modern societies
			on a wide range of information and communications 
			technology (ICT). 
		</paragraph>
		<definitionlist>
			<description>
				In this lesson we look at the following four 
				aspects in more detail: 
			</description>
			<term>
				Critical Infrastructure (CI) 
			</term>
			<definition>
				The so-called critical infrastructure, which 
				underpins many of a country's vital functions, 
				is at most risk, due to the dependence of CI on 
				the uninterrupted functioning of ICT. 
			</definition>

			<term>
				Change in the Risk Environment 
			</term>
			<definition>
				Changes to the international environment since 
				the end of the Cold War have fundamentally 
				changed the theory and practice of security. The
				malicious use of ICT, either as a target or as a
				tool used by a wide range of malevolent actors, 
				defies traditional threat analysis. Compared to 
				traditional security threat analysis, which 
				discusses security in terms of actors, their 
				intentions, and their capabilities, 
				cyber-threats are typically seen as much more 
				complex. 
			</definition>

			<term>
				Malicious Actors 
			</term>
			<definition>
				Hackers, script kiddies, insiders, terrorists, 
				and state sponsored actors are examples of 
				individuals and/or groups with destructive or 
				harmful intent in the cyber-domain. 
			</definition>

			<term>
				Tools and Methods 
			</term>
			<definition>
				This section introduces common tools and methods
				used for attacks on IT, with a focus on viruses 
				and worms. 
			</definition>

		</definitionlist>
	</learningstep>
	<learningstep>
		<title>
			Exercise 
		</title>
		<paragraph>
			Before continuing, please complete the exercise below. 
		</paragraph>
		<interaction>
			<question>
				What is the common denominator of the many 
				ICT-related security risks today? 
			</question>
			<choice>
				<option correct="true">
					Modern societies are thoroughly 
					dependent on ICT infrastructure. 
				</option>
				<option correct="false">
					The cost associated with fighting worms 
					and viruses always runs into billions of
					dollars. 
				</option>
				<option correct="false">
					Cyber-terrorists always attack from far 
					away. 
				</option>
				<option correct="false">
					The end of the Cold War has increased 
					the dependence of modern societies on 
					the uninterrupted functioning of 
					information services. 
				</option>
			</choice>
		</interaction>
	</learningstep>
	<learningstep>
		<title>
			Critical Infrastructure in Danger 
		</title>
		<paragraph>
			Developed societies are becoming increasingly dependent 
			on the various products and services that make up the 
			so-called critical infrastructure (CI) network. Critical
			infrastructures are physical and IT facilities, 
			networks, and assets whose disruption, damaging, 
			manipulation, or destruction would have a serious impact
			on the health, safety, security, and/or economic 
			well-being of a nation. 
		</paragraph>
		<itemization>
			<description>
				A nation's CI is made up of a number of 
				so-called sectors comprising 
			</description>
			<listitem>
				Energy 
			</listitem>
			<listitem>
				Communications 
			</listitem>
			<listitem>
				Financial systems 
			</listitem>
			<listitem>
				Transportation 
			</listitem>
			<listitem>
				Safety 
			</listitem>
			<listitem>
				Government services 
			</listitem>
		</itemization>
		<paragraph>
			Increasingly, everything, including for example the 
			delivery of energy to homes and businesses and the 
			effectiveness of health care systems, is dependent on 
			the reliability of information systems and networks. 
			These critical information infrastructures (CII) are 
			regarded as the backbone of CI in many countries, given 
			that the uninterrupted communication of data is 
			essential to government operations, emergency services, 
			and commerce. This dependence on information &#x2014; 
			combined with increasing vulnerabilities resulting from 
			technical security gaps, the complexity of technology, 
			ongoing liberalization, the growing ability and 
			willingness of malicious actors to conduct physical and 
			cyber-attacks &#x2014; makes telecommunications and 
			information systems highly vulnerable targets. 
		</paragraph>
		<paragraph>
			It is important to realize that the infrastructures as 
			objects that need protection are not static 
			infrastructures, as such. They are services &#x2014; 
			physical and electronic (information-) flows &#x2014; 
			with a specific role and function within society. 
		</paragraph>
		<paragraph>
			Consider the example of the Sapphire worm at the 
			beginning of the lesson. The peripheral effects of 
			Sapphire scared many government officials, as the worm's
			impact illustrated the potential severity of damage to 
			ICT: Sapphire not only slowed down the Internet, but it 
			also disrupted transportation, communications, emergency
			services, banking, finance, and government services. For
			example, the North American automated teller machine 
			service was intermittently interrupted; several North 
			American airport hubs were forced to postpone or cancel 
			flights, when their online services were disrupted; and 
			a 911 call center outside Seattle, Washington, which 
			services 14 fire departments, two police stations, and a
